version: '3.3'

services:
  nodeserver:
    container_name: server01
    build: .
  nginx:
    container_name: nginx01
    image: nginx:1.15.10-alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - nodeserver